/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Native_MazeSolver */

#ifndef _Included_org_example_Native_MazeSolver
#define _Included_org_example_Native_MazeSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Native_MazeSolver
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_Native_MazeSolver_sayHello
  (JNIEnv *, jclass);

/*
 * Class:     org_example_Native_MazeSolver
 * Method:    returnHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_Native_MazeSolver_returnHello
  (JNIEnv *, jclass);

/*
 * Class:     org_example_Native_MazeSolver
 * Method:    InitializeMaze
 * Signature: ([[I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_example_Native_MazeSolver_InitializeMaze
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_example_Native_MazeSolver
 * Method:    AStar
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_example_Native_MazeSolver_AStar
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
