/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Models_Maze */

#ifndef _Included_org_example_Models_Maze
#define _Included_org_example_Models_Maze
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Models_Maze
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_Models_Maze_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
